name: Deploy to Namecheap
on:
  push:
    branches:
      - master  # Trigger deployment when pushing to the master branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Namecheap
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          ftp-server: ftp://your-ftp-server
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Path to your project files
          remote-dir: /public_html/github/